name: tests-rnd

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-toy-configs:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'skip-ci') }}

    strategy:
      matrix:
        include:
          - config: '+id=000 data.fpred=../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/f0.test.pred        "fair.algorithm=[fa-ir, det_greedy, det_relaxed, det_const_sort, det_cons]" "fair.notion=[eo,dp]" "fair.attribute=[gender, popularity]" "fair.is_popular_alg=[avg, auc]"'
          - config: '+id=001 data.fpred=../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/ acceleration=cpu:1 "fair.algorithm=[fa-ir, det_greedy, det_relaxed, det_const_sort, det_cons]" "fair.notion=[eo,dp]" "fair.attribute=[gender, popularity]" "fair.is_popular_alg=[avg, auc]"'
          - config: '+id=002 data.fpred=../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/ acceleration=cpu:3 "fair.algorithm=[fa-ir, det_greedy, det_relaxed, det_const_sort, det_cons]" "fair.notion=[eo,dp]" "fair.attribute=[gender, popularity]" "fair.is_popular_alg=[avg, auc]"'
          - config: '+id=003 data.fpred=../output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/ acceleration=cpu   "fair.algorithm=[fa-ir, det_greedy, det_relaxed, det_const_sort, det_cons]" "fair.notion=[eo,dp]" "fair.attribute=[gender, popularity]" "fair.is_popular_alg=[avg, auc]"'

      # Set to false if you want parallel runs:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Clean up previous outputs
        run: rm -rf output/dblp/toy.dblp.v12.json/splits.f3.r0.85/rnd.b1000/adila/

      - name: Echo config index
        run: |
          echo 'Config index: ${{ matrix.index }}'

      - name: Run config ${{ matrix.config }}
        run: |
          python main.py ${{ matrix.config }}
        working-directory: ./src
        continue-on-error: ${{ matrix.label == 'fail.validate' }}

